### ISSUE TITLE
建议完善资源文件的生成教程

### ISSUE THREAD

**Issue by kay2cc** [qmjy/mapbox-offline-server#1]
最近在研究地图知识，项目给了很多思路和具体的实践。真的是宝藏项目，为作者👍
在地图领域自己还是个新手，对功能的不理解可以通过阅读源码进行了解。
资源方面就束手无策了，希望作者能编写一些资源方面的教程或提供资源源文件。

求联系方式，参加到项目的建设中！

**Comment by qmjy** [comment]
我拉个QQ群吧。

**Comment by qmjy** [comment]
QQ群已建好，有问题可以入群聊。群在README主页。
